lan:
  hosts:
    infra:
    infra-2:

dmz:
  hosts:

router:
  hosts: 
    gateway:

dns:
  hosts:
    gateway:

ntp:
  hosts:
    gateway:

ca:
  hosts:
    gateway:

kanidm:
  hosts:
    infra-2:

vpn:
  hosts:
    gateway: